{
  "version": "5",
  "dialect": "postgresql",
  "id": "d6b55a97-1379-473d-a43f-e9482e93f3fc",
  "prevId": null,
  "steps": [
    {
      "tag": "CreateEnum",
      "enum": "TaskStatus",
      "values": [
        "TODO",
        "IN_PROGRESS",
        "DONE"
      ]
    },
    {
      "tag": "CreateModel",
      "model": "User"
    },
    {
      "tag": "CreateField",
      "model": "User",
      "field": "id",
      "type": "String",
      "arity": "Required"
    },
    {
      "tag": "CreateField",
      "model": "User",
      "field": "email",
      "type": "String",
      "arity": "Required"
    },
    {
      "tag": "CreateField",
      "model": "User",
      "field": "password",
      "type": "String",
      "arity": "Required"
    },
    {
      "tag": "CreateField",
      "model": "User",
      "field": "name",
      "type": "String",
      "arity": "Optional"
    },
    {
      "tag": "CreateField",
      "model": "User",
      "field": "createdAt",
      "type": "DateTime",
      "arity": "Required"
    },
    {
      "tag": "CreateDirective",
      "location": {
        "path": {
          "tag": "Field",
          "model": "User",
          "field": "createdAt"
        },
        "directive": "default"
      }
    },
    {
      "tag": "CreateArgument",
      "location": {
        "tag": "Directive",
        "path": {
          "tag": "Field",
          "model": "User",
          "field": "createdAt"
        },
        "directive": "default"
      },
      "argument": "",
      "value": "now()"
    },
    {
      "tag": "CreateField",
      "model": "User",
      "field": "updatedAt",
      "type": "DateTime",
      "arity": "Required"
    },
    {
      "tag": "CreateDirective",
      "location": {
        "path": {
          "tag": "Field",
          "model": "User",
          "field": "updatedAt"
        },
        "directive": "updatedAt"
      }
    },
    {
      "tag": "CreateField",
      "model": "User",
      "field": "tasks",
      "type": "Task",
      "arity": "List"
    },
    {
      "tag": "CreateModel",
      "model": "Task"
    },
    {
      "tag": "CreateField",
      "model": "Task",
      "field": "id",
      "type": "String",
      "arity": "Required"
    },
    {
      "tag": "CreateField",
      "model": "Task",
      "field": "title",
      "type": "String",
      "arity": "Required"
    },
    {
      "tag": "CreateField",
      "model": "Task",
      "field": "description",
      "type": "String",
      "arity": "Optional"
    },
    {
      "tag": "CreateField",
      "model": "Task",
      "field": "status",
      "type": "TaskStatus",
      "arity": "Required"
    },
    {
      "tag": "CreateDirective",
      "location": {
        "path": {
          "tag": "Field",
          "model": "Task",
          "field": "status"
        },
        "directive": "default"
      }
    },
    {
      "tag": "CreateArgument",
      "location": {
        "tag": "Directive",
        "path": {
          "tag": "Field",
          "model": "Task",
          "field": "status"
        },
        "directive": "default"
      },
      "argument": "",
      "value": "TODO"
    },
    {
      "tag": "CreateField",
      "model": "Task",
      "field": "createdAt",
      "type": "DateTime",
      "arity": "Required"
    },
    {
      "tag": "CreateDirective",
      "location": {
        "path": {
          "tag": "Field",
          "model": "Task",
          "field": "createdAt"
        },
        "directive": "default"
      }
    },
    {
      "tag": "CreateArgument",
      "location": {
        "tag": "Directive",
        "path": {
          "tag": "Field",
          "model": "Task",
          "field": "createdAt"
        },
        "directive": "default"
      },
      "argument": "",
      "value": "now()"
    },
    {
      "tag": "CreateField",
      "model": "Task",
      "field": "updatedAt",
      "type": "DateTime",
      "arity": "Required"
    },
    {
      "tag": "CreateDirective",
      "location": {
        "path": {
          "tag": "Field",
          "model": "Task",
          "field": "updatedAt"
        },
        "directive": "updatedAt"
      }
    },
    {
      "tag": "CreateField",
      "model": "Task",
      "field": "userId",
      "type": "String",
      "arity": "Required"
    },
    {
      "tag": "CreateField",
      "model": "Task",
      "field": "user",
      "type": "User",
      "arity": "Required"
    },
    {
      "tag": "CreateDirective",
      "location": {
        "path": {
          "tag": "Field",
          "model": "Task",
          "field": "user"
        },
        "directive": "relation"
      }
    },
    {
      "tag": "CreateArgument",
      "location": {
        "tag": "Directive",
        "path": {
          "tag": "Field",
          "model": "Task",
          "field": "user"
        },
        "directive": "relation"
      },
      "argument": "fields",
      "value": "[userId]"
    },
    {
      "tag": "CreateArgument",
      "location": {
        "tag": "Directive",
        "path": {
          "tag": "Field",
          "model": "Task",
          "field": "user"
        },
        "directive": "relation"
      },
      "argument": "references",
      "value": "[id]"
    },
    {
      "tag": "CreateArgument",
      "location": {
        "tag": "Directive",
        "path": {
          "tag": "Field",
          "model": "Task",
          "field": "user"
        },
        "directive": "relation"
      },
      "argument": "onDelete",
      "value": "Cascade"
    }
  ]
}
